# Copyright (C) 2026 zurek-jiri and contributors.
# SPDX-License-Identifier: AGPL-3.0-only
# See LICENSE and COPYRIGHT for terms and the no-warranty notice.

"""Prepare the static project site; no network calls or publication."""
import argparse
import json
from pathlib import Path
import re
import shutil


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository", default="", help="GitHub OWNER/REPOSITORY, or omit for local preview")
    parser.add_argument("--output", default="_site", help="New output folder inside this project")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    target = (root / args.output).resolve()
    if root not in target.parents or target == root / "site" or (root / "site") in target.parents:
        parser.error("Output must be a separate folder inside this project, outside site/.")
    marker = target / ".temperament-site-output"
    if target.exists() and any(target.iterdir()) and not marker.is_file():
        parser.error("Refusing to overwrite an existing folder that was not created by this tool.")
    if args.repository and not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9-]*/[A-Za-z0-9_.-]+", args.repository):
        parser.error("Repository must be a GitHub OWNER/REPOSITORY name.")
    match = re.search(r"project\(TemperamentGenerator VERSION (\d+\.\d+\.\d+)", (root / "CMakeLists.txt").read_text())
    if not match:
        parser.error("Could not read the application version from CMakeLists.txt.")
    shutil.copytree(root / "site", target, dirs_exist_ok=True)
    (target / "config.js").write_text("window.temperamentSite = " + json.dumps({
        "repository": args.repository, "version": match.group(1),
        "hasLicense": (root / "LICENSE").is_file(), "localDocs": "docs/"
    }) + ";\n", encoding="utf-8")
    if not args.repository:
        for name in ("README.md", "CONTRIBUTING.md", "docs/BUILDING.md"):
            destination = target / "docs" / name
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(root / name, destination)
    marker.write_text("Generated by Tools/prepare_site.py.\n", encoding="utf-8")
    (target / ".nojekyll").touch()
    print("Website prepared at " + str(target / "index.html"))
    print("No files were uploaded or published.")


if __name__ == "__main__":
    main()
