# Copyright (C) 2026 zurek-jiri and contributors.
# SPDX-License-Identifier: AGPL-3.0-only
"""Losslessly pack the supplied Principal8 WAVs; ffmpeg is only a maintainer tool."""
import hashlib
import json
from pathlib import Path
import struct
import subprocess

root = Path(__file__).resolve().parent.parent
destination = root / 'Source/PrincipalSamples'
destination.mkdir(parents=True, exist_ok=True)
records = []
for note in range(48, 73):
    sources = [p for p in (root / 'Principal8').glob(f'{note:03d}-*.wav') if not p.stem.endswith('_a')]
    if len(sources) != 1:
        raise SystemExit(f'Expected exactly one primary recording for note {note}.')
    source = sources[0]
    data = source.read_bytes()
    offset, loops, pcm, fmt = 12, [], b'', None
    while offset + 8 <= len(data):
        tag, length = struct.unpack_from('<4sI', data, offset)
        chunk = data[offset+8:offset+8+length]
        if tag == b'fmt ':
            fmt = struct.unpack_from('<HHIIHH', chunk)
        elif tag == b'data':
            pcm = chunk
        elif tag == b'smpl':
            for index in range(struct.unpack_from('<I', chunk, 28)[0]):
                _, kind, start, end, _, _ = struct.unpack_from('<6I', chunk, 36+24*index)
                if kind == 0 and end > start:
                    loops.append([start, end+1])  # WAV ends are inclusive.
        offset += 8 + length + length % 2
    assert fmt and fmt[0] == 1 and fmt[1] == 1 and fmt[5] == 24 and pcm
    output = destination / f'note{note:03d}.flac'
    subprocess.run(['ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', '-i', str(source),
        '-map_metadata', '-1', '-c:a', 'flac', '-compression_level', '12', str(output)], check=True)
    decoded = subprocess.check_output(['ffmpeg', '-hide_banner', '-loglevel', 'error', '-i', str(output),
        '-f', 's24le', '-acodec', 'pcm_s24le', '-'])
    assert decoded == pcm, 'Lossless PCM verification failed: ' + source.name
    frames = len(pcm)//3
    loop = next((pair for pair in loops if pair[1] <= frames), [0, 0])
    records.append(dict(note=note, original=source.name, file=output.name, sampleRate=fmt[2],
        frames=frames, loop=loop, pcmSha256=hashlib.sha256(pcm).hexdigest(),
        flacSha256=hashlib.sha256(output.read_bytes()).hexdigest()))
(destination/'manifest.json').write_text(json.dumps(records, indent=2)+'\n', encoding='utf-8')
header = '// Generated by Tools/prepare_samples.py from supplied WAV loop metadata.\n#pragma once\n#include <array>\nnamespace principal {\nstruct Metadata { int frames, loopStart, loopEnd; double rate; };\ninline constexpr std::array<Metadata,25> metadata {{\n'
header += ''.join('    {' + ', '.join(map(str, [r['frames'], *r['loop'], r['sampleRate']])) + '},\n' for r in records)
(destination/'SampleMetadata.h').write_text(header+'}};\n}\n', encoding='utf-8')
print('25 recordings packed and verified lossless; total FLAC bytes:', sum((destination/r['file']).stat().st_size for r in records))
